/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-02-28 04:45:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Loginindex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1614487312689L));
    _jspx_dependants.put("jar:file:/C:/Users/zmffh/OneDrive/Desktop/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/NewFolderProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<!--\r\n");
      out.write("\tAesthetic by gettemplates.co\r\n");
      out.write("\tTwitter: http://twitter.com/gettemplateco\r\n");
      out.write("\tURL: http://gettemplates.co\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>Savory &mdash; Free Website Template, Free HTML5 Template\r\n");
      out.write("\tby GetTemplates.co</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Free HTML5 Website Template by GetTemplates.co\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive\" />\r\n");
      out.write("<meta name=\"author\" content=\"GetTemplates.co\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Facebook and Twitter integration -->\r\n");
      out.write("<meta property=\"og:title\" content=\"\" />\r\n");
      out.write("<meta property=\"og:image\" content=\"\" />\r\n");
      out.write("<meta property=\"og:url\" content=\"\" />\r\n");
      out.write("<meta property=\"og:site_name\" content=\"\" />\r\n");
      out.write("<meta property=\"og:description\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:title\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:image\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:url\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:card\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Kaushan+Script\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Animate.css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/animate.css\">\r\n");
      out.write("<!-- Icomoon Icon Fonts-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/icomoon.css\">\r\n");
      out.write("<!-- Themify Icons-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/themify-icons.css\">\r\n");
      out.write("<!-- Bootstrap  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap DateTimePicker -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/bootstrap-datetimepicker.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Owl Carousel  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Theme style  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Modernizr JS -->\r\n");
      out.write("<script src=\"./resources/js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("<!-- FOR IE9 below -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"gtco-loader\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- <div class=\"page-inner\"> -->\r\n");
      out.write("\t\t<nav class=\"gtco-nav\" role=\"navigation\">\r\n");
      out.write("\t\t\t<div class=\"gtco-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"gtco-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"index\">New Folder <em>.</em></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-8 text-right menu-1\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"has-dropdown\"><a href=\"GetFoodsInfo\">Contents</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"GetFoodsInfo\">VS Game</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"RandomRecommendControll\">Recommend</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"getTopFoodsInfo\">Top Ranks</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"has-dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"FoodsInfoControll?foodeCode=01\">Foods</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"FoodsInfoControll?foodeCode=01\">Korean\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tFoods</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"FoodsInfoControll?foodeCode=02\">Western\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tFoods</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"FoodsInfoControll?foodeCode=03\">Chinese\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tFoods</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"FoodsInfoControll?foodeCode=04\">Asian\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tFoods</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"FoodsInfoControll?foodeCode=05\">Fast\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tFoods</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"FoodsInfoControll?foodeCode=06\">Coffee&Dessert</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a href=\"foods.html\">Foods</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"GetCouponInfo\">Event</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"community\">Community</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"btn-cta\"><a href=\"index\"><span>Sign-up</span></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t<header id=\"gtco-header\" class=\"gtco-cover gtco-cover-md\"\r\n");
      out.write("\t\t\trole=\"banner\" style=\"background-image: url(./resources/images/img_bg_1.jpg)\"\r\n");
      out.write("\t\t\tdata-stellar-background-ratio=\"0.5\">\r\n");
      out.write("\t\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t\t<div class=\"gtco-container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 col-md-offset-0 text-left\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row row-mt-15em\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-7 mt-text animate-box\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-animate-effect=\"fadeInUp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"intro-text-small\">The greatest problem ever\r\n");
      out.write("\t\t\t\t\t\t\t\t\tI thought...</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1 class=\"cursive-font\">What should we eat today?</h1>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-4 col-md-push-1 animate-box\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-animate-effect=\"fadeInRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tab\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"tab-content-inner active\" data-content=\"signup\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"cursive-font\">Sign-in</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<form action=\"logInControll\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>ID</label> <input type=\"text\" id=\"ID\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" required autofocus\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"type your ID\" name=\"id\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Password</label> <input type=\"Password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"Password\" class=\"form-control\" required\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"type your PW\" name=\"pwd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"Loginbtn\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary btn-block\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"Sign-in\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"gtco-counter\" class=\"gtco-section\">\r\n");
      out.write("\t\t\t<div class=\"gtco-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-md-8 col-md-offset-2 text-center gtco-heading animate-box\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"cursive-font primary-color\">Today</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Thanks for use :)</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-6 animate-box\"\r\n");
      out.write("\t\t\t\t\t\tdata-animate-effect=\"fadeInUp\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"counter js-counter\" data-from=\"0\" data-speed=\"5000\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-refresh-interval=\"50\" id=\"todaylogin\">1</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"counter-label\">Log-in</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-6 animate-box\"\r\n");
      out.write("\t\t\t\t\t\tdata-animate-effect=\"fadeInUp\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"counter js-counter\" data-from=\"0\" data-speed=\"5000\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-refresh-interval=\"50\" id=\"todaygame\">1</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"counter-label\">VS Game</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-6 animate-box\"\r\n");
      out.write("\t\t\t\t\t\tdata-animate-effect=\"fadeInUp\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"counter js-counter\" data-from=\"0\" data-speed=\"5000\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-refresh-interval=\"50\" id=\"totalstore\">1</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"counter-label\">Stores</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-6 animate-box\"\r\n");
      out.write("\t\t\t\t\t\tdata-animate-effect=\"fadeInUp\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"counter js-counter\" data-from=\"0\" data-speed=\"5000\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-refresh-interval=\"50\" id=\"totalreview\">1</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"counter-label\">Reviews</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"contentsVS\" class=\"gtco-section\">\r\n");
      out.write("\t\t\t<div class=\"gtco-container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-md-offset-2 text-center gtco-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"cursive-font primary-color\">Contents</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>You can do eat</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./resources/images/vs4.png\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"./resources/images/vs4.png\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fh5co-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"cursive-font primary-color\" style=\"font-size: 3rem;\">VS\r\n");
      out.write("\t\t\t\t\t\t\t\t\tGame</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>I will help your choice !</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p><span class=\"price cursive-font\">$19.15</span></p> -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./resources/images/gps.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"./resources/images/gps.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fh5co-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"cursive-font primary-color\" style=\"font-size: 3rem;\">Recommend</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>If you are looking for interesting food, Click!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p> Press here !</p> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p><span class=\"price cursive-font\">$20.99</span></p> -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-6\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"padding-bottom: 10vw;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./resources/images/best2.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"./resources/images/best2.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fh5co-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"cursive-font primary-color\" style=\"font-size: 3rem;\">Ranking</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>If you are looking for interesting food, Click!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p> Press here !</p> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p><span class=\"price cursive-font\">$20.99</span></p> -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-md-offset-2 text-center gtco-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"cursive-font primary-color\">Foods</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>What is your choice?</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./resources/images/krfd11.jpeg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"./resources/images/krfd11.jpeg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fh5co-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"cursive-font primary-color\" style=\"font-size: 3rem;\">Korean\r\n");
      out.write("\t\t\t\t\t\t\t\t\tFood</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Enjoy various Korean foods</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p><span class=\"price cursive-font\">$8.99</span></p> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./resources/images/asfd11.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"./resources/images/asfd11.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fh5co-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"cursive-font primary-color\" style=\"font-size: 3rem;\">Asian\r\n");
      out.write("\t\t\t\t\t\t\t\t\tFood</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Thai & Japanese</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p><span class=\"price cursive-font\">$12.99</span></p> -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./resources/images/chfd.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"./resources/images/chfd.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fh5co-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"cursive-font primary-color\" style=\"font-size: 3rem;\">Chinese\r\n");
      out.write("\t\t\t\t\t\t\t\t\tFood</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Enjoy various Chinese foods</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p><span class=\"price cursive-font\">$23.10</span></p> -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./resources/images/wtfd.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"./resources/images/wtfd.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fh5co-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"cursive-font primary-color\" style=\"font-size: 3rem;\">Western\r\n");
      out.write("\t\t\t\t\t\t\t\t\tFood</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Enjoy various Western foods</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p><span class=\"price cursive-font\">$5.59</span></p> -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./resources/images/ftfd5.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"./resources/images/ftfd5.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fh5co-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"cursive-font primary-color\" style=\"font-size: 3rem;\">Fast\r\n");
      out.write("\t\t\t\t\t\t\t\t\tFood</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Enjoy various Korean foods</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p><span class=\"price cursive-font\">$8.99</span></p> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./resources/images/cfdt2.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"./resources/images/cfdt2.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fh5co-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"cursive-font primary-color\" style=\"font-size: 3rem;\">Coffee\r\n");
      out.write("\t\t\t\t\t\t\t\t\t& Dessert</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Enjoy various Korean foods</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p><span class=\"price cursive-font\">$8.99</span></p> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"gtco-features\">\r\n");
      out.write("\t\t\t<div class=\"gtco-container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-md-8 col-md-offset-2 text-center gtco-heading animate-box\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"cursive-font\">Our Services</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\tWe have been always worried What should we eat today?</br> But from\r\n");
      out.write("\t\t\t\t\t\t\tnow on, Don't worry about it anymore\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>Just do eat !</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature-center animate-box\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-animate-effect=\"fadeIn\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon\"> <a href=\"#contentsVS\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"ti-face-smile\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Is eat fun? It is fun!</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tTry ”VS game” !</br> If choosing the menu make you stressed out!\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature-center animate-box\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-animate-effect=\"fadeIn\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon\"> <a href=\"#contentsVS\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"ti-thought\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Where are you?</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tClick the 'recommend' and then look around!</br> You'll find a good\r\n");
      out.write("\t\t\t\t\t\t\t\tplace that you didn't know.\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"feature-center animate-box\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-animate-effect=\"fadeIn\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon\"> <a href=\"#gtco-subscribe\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"ti-truck\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>You are lucky !</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tAs soon as press the ”APPLY”</br> You can get something lucky!\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"gtco-cover gtco-cover-sm\"\r\n");
      out.write("\t\t\tstyle=\"background-image: url(./resources/images/img_bg_1.jpg)\"\r\n");
      out.write("\t\t\tdata-stellar-background-ratio=\"0.5\">\r\n");
      out.write("\t\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t\t<div class=\"gtco-container text-center\">\r\n");
      out.write("\t\t\t\t<div class=\"display-t\">\r\n");
      out.write("\t\t\t\t\t<div class=\"display-tc\">\r\n");
      out.write("\t\t\t\t\t\t<h1>&ldquo; Just do eat &rdquo;</h1>\r\n");
      out.write("\t\t\t\t\t\t<p>&mdash; New Folder of ICIA.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- <div id=\"gtco-counter\" class=\"gtco-section\">\r\n");
      out.write("\t\t<div class=\"gtco-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-md-offset-2 text-center gtco-heading animate-box\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"cursive-font primary-color\">Fun Facts</h2>\r\n");
      out.write("\t\t\t\t\t<p>Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-sm-6 animate-box\" data-animate-effect=\"fadeInUp\">\r\n");
      out.write("\t\t\t\t\t<div class=\"feature-center\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"counter js-counter\" data-from=\"0\" data-to=\"5\" data-speed=\"5000\" data-refresh-interval=\"50\">1</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"counter-label\">Avg. Rating</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-sm-6 animate-box\" data-animate-effect=\"fadeInUp\">\r\n");
      out.write("\t\t\t\t\t<div class=\"feature-center\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"counter js-counter\" data-from=\"0\" data-to=\"43\" data-speed=\"5000\" data-refresh-interval=\"50\">1</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"counter-label\">Food Types</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-sm-6 animate-box\" data-animate-effect=\"fadeInUp\">\r\n");
      out.write("\t\t\t\t\t<div class=\"feature-center\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"counter js-counter\" data-from=\"0\" data-to=\"32\" data-speed=\"5000\" data-refresh-interval=\"50\">1</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"counter-label\">Chef Cook</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-sm-6 animate-box\" data-animate-effect=\"fadeInUp\">\r\n");
      out.write("\t\t\t\t\t<div class=\"feature-center\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"counter js-counter\" data-from=\"0\" data-to=\"1985\" data-speed=\"5000\" data-refresh-interval=\"50\">1</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"counter-label\">Year Started</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"gtco-subscribe\">\r\n");
      out.write("\t\t\t<div class=\"gtco-container\">\r\n");
      out.write("\t\t\t\t<div class=\"row animate-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-md-offset-2 text-center gtco-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"cursive-font\">now on 10% off</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\tNow on events</br> Get a specail price on here !\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row animate-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-md-offset-4\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-inline\" action=\"isCouponApply\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default btn-block\">Apply</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<footer id=\"gtco-footer\" role=\"contentinfo\"\r\n");
      out.write("\t\t\tstyle=\"background-image: url(./resources/images/img_bg_1.jpg)\"\r\n");
      out.write("\t\t\tdata-stellar-background-ratio=\"0.5\">\r\n");
      out.write("\t\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t\t<div class=\"gtco-container\">\r\n");
      out.write("\t\t\t\t<div class=\"row row-pb-md\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"gtco-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Get In Touch</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"gtco-quick-contact\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-phone\"></i> 010 2190\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t4168</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-mail2\"></i>kdh4168@naver.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-chat\"></i><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"kakaoID1\">Kakao</span></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"gtco-quick-contact\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-phone\"></i> 010 3740\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t6894</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-mail2\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmoonsj6894@naver.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-chat\"></i><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"kakaoID2\">Kakao</span></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"gtco-quick-contact\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-phone\"></i>010 9525 1639 </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-mail2\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tgmlans9525@naver.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-chat\"></i><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"kakaoID3\">Kakao</span></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"gtco-quick-contact\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-phone\"></i> 010 6615 0501</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-mail2\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tspqjeks@naver.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-chat\"></i><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"kakaoID4\">Kakao</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\tvar kakaoid1 = document.getElementById(\"kakaoID1\")\r\n");
      out.write("\t\t\t\t\t\t\t\tkakaoid1.addEventListener(\"mouseover\",()=>{kakaoid1.innerHTML=\"강동훈\"});\r\n");
      out.write("\t\t\t\t\t\t\t\tkakaoid1.addEventListener(\"mouseout\",()=>{kakaoid1.innerHTML=\"Kakao\"});\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tvar kakaoid2 = document.getElementById(\"kakaoID2\")\r\n");
      out.write("\t\t\t\t\t\t\t\tkakaoid2.addEventListener(\"mouseover\",()=>{kakaoid2.innerHTML=\"문상진\"});\r\n");
      out.write("\t\t\t\t\t\t\t\tkakaoid2.addEventListener(\"mouseout\",()=>{kakaoid2.innerHTML=\"Kakao\"});\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tvar kakaoid3 = document.getElementById(\"kakaoID3\")\r\n");
      out.write("\t\t\t\t\t\t\t\tkakaoid3.addEventListener(\"mouseover\",()=>{kakaoid3.innerHTML=\"유상민\"});\r\n");
      out.write("\t\t\t\t\t\t\t\tkakaoid3.addEventListener(\"mouseout\",()=>{kakaoid3.innerHTML=\"Kakao\"});\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tvar kakaoid4 = document.getElementById(\"kakaoID4\")\r\n");
      out.write("\t\t\t\t\t\t\t\tkakaoid4.addEventListener(\"mouseover\",()=>{kakaoid4.innerHTML=\"조 단\"});\r\n");
      out.write("\t\t\t\t\t\t\t\tkakaoid4.addEventListener(\"mouseout\",()=>{kakaoid4.innerHTML=\"Kakao\"});\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"gtco-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Get Social</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"gtco-social-icons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-linkedin\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-dribbble\"></i></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 text-center copyright\">\r\n");
      out.write("\t\t\t\t\t\tMade by <i class=\"fa fa-love\"></i><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#\">New Folder</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t<!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"gototop js-top\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"js-gotop\"><i class=\"icon-arrow-up\"></i></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"./resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery Easing -->\r\n");
      out.write("\t<script src=\"./resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<script src=\"./resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Waypoints -->\r\n");
      out.write("\t<script src=\"./resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Carousel -->\r\n");
      out.write("\t<script src=\"./resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<!-- countTo -->\r\n");
      out.write("\t<script src=\"./resources/js/jquery.countTo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Stellar Parallax -->\r\n");
      out.write("\t<script src=\"./resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Magnific Popup -->\r\n");
      out.write("\t<script src=\"./resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"./resources/js/magnific-popup-options.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"./resources/js/moment.min.js\"></script>\r\n");
      out.write("\t<script src=\"./resources/js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main -->\r\n");
      out.write("\t<script src=\"./resources/js/main.js\"> </script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t   $(document).ready(function () {\r\n");
      out.write("\t\t        $.ajax({ \r\n");
      out.write("\t\t            url : \"LoadControll\",\r\n");
      out.write("\t\t            type: \"post\",\r\n");
      out.write("\t\t            datatype : \"json\",\r\n");
      out.write(" \t\t            success : function (data) {\r\n");
      out.write("\t\t      \t\t\tconsole.log(data)\r\n");
      out.write("\t\t      \t\t\t$(\"#todaylogin\").attr('data-to',data.todayLogin);\r\n");
      out.write("\t\t            \t$(\"#todaygame\").attr('data-to',data.todayGames);\r\n");
      out.write("\t\t            \t$(\"#totalstore\").attr('data-to',data.totalStores);\r\n");
      out.write("\t\t            \t$(\"#totalreview\").attr('data-to',data.totalReviews);\r\n");
      out.write("\t\t            },\r\n");
      out.write("\t\t            error : function (data) {\r\n");
      out.write("                         // 실패 할 경우 안내구문\r\n");
      out.write("\t\t                alert(\"데이터를 불러올수없습니다.\");\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
